---
ubuntu_version: 18.04
interface: "{{ ansible_default_ipv4['interface'] }}"
address: "{{ ansible_default_ipv4['address'] }}"
netmask: "{{ ansible_default_ipv4['netmask'] }}"
gateway: "{{ ansible_default_ipv4['gateway'] }}"
