---
# 生成uuid
- name: create uuid
  include_tasks: uuid/main.yml

# 查找yml配置文件
- name: find yml config
  include_tasks: config/main.yml

# 计算子网掩码
- name: caculate netmask
  include_tasks: netmask/main.yml

# 生成配置文件
- name: create Debian
  include_tasks: Debian.yml

- name: config RedHat
  include_tasks: RedHat.yml
