##
# 安装alertmanager
#
#
##
# @leif160519 @2020.09.20
####
---
- name: 安装alertmanager
  hosts: all
  tags: [alertmanager]
  vars:
    a_version: 0.21.0
    a_md5sum: 6eed1c4c3b6678aff20557fc5cc27f4a
  tasks:
    - name: prometheus
      block:
        - user:
            name: prometheus

        - group: 
            name: prometheus

        - stat:
            path: /opt/alertmanager
          register: a

        - get_url:
            #url: https://github.com/prometheus/alertmanager/releases/download/v0.21.0/alertmanager-{{ a_version }}.linux-amd64.tar.gz
            url: http://10.1.1.26/repository/it/prometheus/alertmanager-{{ a_version }}.linux-amd64.tar.gz
            dest: /tmp/alertmanager-{{ a_version }}.linux-amd64.tar.gz
            checksum: md5:{{ a_md5sum }}
          when: a.stat.exists == false

        - unarchive: 
            copy: false
            src: /tmp/alertmanager-{{ a_version }}.linux-amd64.tar.gz
            dest: /opt
            owner: prometheus
            group: prometheus
          when: a.stat.exists == false

        - command: mv /opt/alertmanager-{{ a_version }}.linux-amd64 /opt/alertmanager
          when: a.stat.exists == false

        - lineinfile: # 配置alertmanager地址
            dest: /opt/prometheus/prometheus.yml
            regexp: '      # - alertmanager:9093'
            line: "        - {{ ansible_default_ipv4['address'] }}:9093"

        - set_fact:
            service_name: alertmanager
            command: /opt/alertmanager/alertmanager --config.file=/opt/alertmanager/alertmanager.yml

        - template:
            src: files/service/service.service
            dest: /lib/systemd/system/{{ service_name }}.service
            mode: 0644

        - service:
            name: "{{ service_name }}"
            state: started
            enabled: yes

        - raw: kill -HUP `ps -e | grep prometheus | awk '{print $1}'`
          ignore_errors: yes
          run_once: true

        - file:
            path: /tmp/alertmanager-{{ a_version }}.linux-amd64.tar.gz
            state: absent
