##
# 安装Docker
#
#
##
# @leif160519 @2020.08.29
####
---
- name: Ubuntu 安装Docker
  hosts: dist.ubuntu.lts
  tags: [ubuntu, lts, docker]
  tasks:
    - name: 安装Docker和Docker-compose
      apt:
        name: ['docker.io','docker-compose']
        state: latest
    - name:  清理不再使用的依赖包
      apt:
        autoremove: yes
    - name: 清理下载的安装包缓存
      shell: apt clean && apt autoclean
      ignore_errors: yes


- name: Centos 7 安装Docker
  hosts: dist.centos7
  tags: [centos, seven, docker]
  tasks:
    - name: 安装Docker和Docker-compose
      yum:
        name: ['docker-ce','docker-compose']
        state: installed
    - name: 清理安装包
      shell: yum clean all
      ignore_errors: true

- name: 配置Docker
  hosts: all
  tasks:
    - name: 配置仓库源和Docker网段
      template:
        src: files/docker/daemon.json
        dest: /etc/docker/
    - name: 启动Docker服务并设置开机自启
      service:
        name: docker
        state: restarted
        enabled: yes
