##
# 安装Docker
#
#
##
# @leif160519 @2020.08.29
####
---
- name: 安装Docker
  hosts: all
  tags: [docker]
  tasks:
    - name: 安装Docker和Docker-compose # {{{ | Debian
      apt:
        name: ['docker.io','docker-compose']
        state: latest
      when: ansible_os_family == "Debian"
      # }}}

    - name: 配置Docker源 # {{{ | redhat
      template:
        src: files/docker/docker-ce.repo
        dest: /etc/yum.repos.d/docker-ce.repo
        mode: 0644
      when: ansible_os_family == "RedHat"
      # }}}

    - name: 安装Docker和Docker-compose  # {{{ | redhat
      yum:
        name: ['docker-ce','docker-compose']
        state: installed
      when: ansible_os_family == "RedHat"
      # }}}

    - name: 清理不再使用的依赖包 # {{{ | Debian
      apt:
        autoremove: yes
      when: ansible_os_family == "Debian"
      # }}}

    - name: 清理下载的安装包缓存 # {{{ | Debian
      shell: apt clean && apt autoclean
      ignore_errors: yes
      when: ansible_os_family == "Debian"
      # }}}

    - name: 清理下载的安装包缓存 # {{{ | redhat
      shell: yum clean all
      ignore_errors: true
      when: ansible_os_family == "RedHat"
      # }}}

    - name: 配置仓库源和Docker网段 # {{{
      vars:
        address: 198.18.0.0/16
        size: 24
        mirrors1: http://hub-mirror.c.163.com
        mirrors2: https://b9pmyelo.mirror.aliyuncs.com
        mirrors3: http://docker.mirrors.ustc.edu.cn
        mirrors4: https://registry.docker-cn.com
      template:
        src: files/docker/daemon.json
        dest: /etc/docker/
        mode: 0644
      # }}}

    - name: 启动Docker服务并设置开机自启  # {{{
      service:
        name: docker
        state: restarted
        enabled: yes
      # }}}
