##
# 安装gitlab
#
#
##
# @leif160519 @2020.08.29
####
---
- name: 安装gitlab
  hosts: dist.centos7
  tags: [gitlab]
  vars:
    gitlab_version: 13.3.2
    gitlab_md5sum: 56562145dcf67e5f242518b49a03adcd
  tasks:
    - name: gitlab
      block:
        - get_url:
            url: https://mirrors.tuna.tsinghua.edu.cn/gitlab-ce/yum/el7/gitlab-ce-{{ gitlab_version }}-ce.0.el7.x86_64.rpm
            dest: /tmp/gitlab-ce-{{ gitlab_version }}-ce.0.el7.x86_64.rpm
            checksum: md5:{{ gitlab_md5sum }}
          when: ansible_machine=="x86_64"

        - yum: 
            name: /tmp/gitlab-ce-{{ gitlab_version }}-ce.0.el7.x86_64.rpm

        - lineinfile:
            dest: /etc/gitlab/gitlab.rb
            regexp: '^external_url'
            line: "external_url 'http://{{ ansible_host }}'"

        - lineinfile:
            dest: /etc/gitlab/gitlab.rb
            regexp: "^# gitlab_rails['backup_keep_time'] ="
            line: "gitlab_rails['backup_keep_time'] = 604800"

        - lineinfile:
            dest: /etc/crontab
            line: '0  2    * * *   root    /opt/gitlab/bin/gitlab-rake gitlab:backup:create CRON=1'

        - shell: | 
            crontab /etc/crontab
            gitlab-ctl reconfigure
          ignore_errors: true
