##
# 安装grafana
#
#
##
# @leif160519 @2020.09.12
####
---
- name: 安装grafana
  hosts: all
  tags: [grafana]
  vars:
    g_version: 7.1.5
    g_md5sum_deb: f27d81974ce84a72b33ab41358258d70
    g_md5sum_rpm: bc96c8d10d40bef833eea3853455ea21 
  tasks:
    - name: grafana
      block:
        - stat:
            path: "/tmp/grafana*{{ g_version }}*.*"
          register: g

        - package: 
            name: "{{ item }}"
          with_items:
            - adduser
            - libfontconfig1
          when: ansible_os_family == "Debian"

        - get_url:
            url: https://dl.grafana.com/oss/release/grafana_{{ g_version }}_amd64.deb
            dest: /tmp/grafana_{{ g_version }}_amd64.deb
            checksum: md5:{{ g_md5sum_deb }}
          when: g.stat.exists == false and ansible_os_family == "Debian"

        - get_url:
            url: https://dl.grafana.com/oss/release/grafana-{{ g_version }}-1.x86_64.rpm
            dest: /tmp/grafana-{{ g_version }}-1.x86_64.rpm
            checksum: md5:{{ g_md5sum_rpm }}
          when: g.stat.exists == false and ansible_os_family == "RedHat"

        - apt:
            deb: /tmp/grafana_{{ g_version }}_amd64.deb
            state: present
          when: ansible_os_family == "Debian"

          #        - shell: yum -y install /tmp/grafana-{{ g_version }}-1.x86_64.rpm
          #          when: ansible_os_family == "RedHat"

        - yum:
            name: /tmp/grafana-{{ g_version }}-1.x86_64.rpm
            state: present
          when: ansible_os_family == "RedHat"

        - service:
            name: grafana-server
            state: started
            enabled: yes

        - file:
            path: /tmp/grafana*{{ g_version }}*.*
            state: absent
