##
# 安装grafana
#
#
##
# @leif160519 @2020.09.12
####
---
- name: 安装grafana
  hosts: all
  tags: [grafana]
  vars:
    grafana_deb_version: grafana_7.1.5_amd64
    grafana_rpm_version: grafana-7.1.5-1.x86_64
    grafana_deb_url: https://dl.grafana.com/oss/release/{{ grafana_rpm_version }}.deb
    grafana_rpm_url: https://dl.grafana.com/oss/release/{{ grafana_rpm_version }}.rpm
  tasks:
    - name: grafana
      block:
        - package:
            name: "{{ item }}"
          with_items:
            - adduser
            - libfontconfig1
          when: ansible_os_family == "Debian"

        - apt:
            deb: "{{ grafana_deb_url }}"
            state: present
          when: ansible_os_family == "Debian"

        - yum:
            name: "{{ grafana_rpm_url }}"
            state: present
          when: ansible_os_family == "RedHat"

        - service:
            name: grafana-server
            state: started
            enabled: yes
