##
# 安装基础软件
#
#
##
# @leif160519 @2020.08.29
####
---
- name: 安装基础软件
  hosts: all
  tags: [install]
  tasks:
    - name: 安装常用软件 # {{{ | RedHat
      package:
        name: "{{ item }}"
        state: latest
      with_items:
        - yum-utils
        - epel-release
        - nagios
        - nc
        - perf
        - bind-utils
      when: ansible_os_family == "RedHat"
      # }}}

    - name: 安装常用软件 # {{{ | Debian
      package:
        name: "{{ item }}"
      with_items:
        - rar
        - python-pip
        - screenfetch
        - neofetch
      when: ansible_os_family == "Debian"
      # }}}

    - package: # {{{ | Linux通用软件包
        name: "{{ item }}"
        state: latest
      with_items:
        - nano
        - vim
        - emacs
        - zip
        - unzip
        - git
        - bash-completion
        - wget
        - htop
        - iotop
        - nethogs
        - mrtg
        - telnet
        - tree
        - tmux
        - iperf
        - figlet
        - lsof
        - dpkg
        - expect
        - hdparm
        - psmisc
        - fping
        - tcpdump
        - nmap
        - fio
        - strace
        - sysstat
        - lrzsz
        - monit
        - ansible
        - dosfstools
        - iftop
        - uuid
        - make
        - colordiff
        - subnetcalc
        - groovy
        - python
        - python3
        - python3-pip
        - w3m
        - lynx
        - dos2unix
        - nethogs
        - curl
        - nload # 流量监控 nload -u M <network_interface>
        - cifs-utils # windows 文件系统支持
        - xfsprogs # xfs文件系统支持
        - exfat-utils # exfat 文件系统支持
        - net-tools # 网络工具
      ignore_errors: yes
      # }}}

    - name: 启动相关服务 # {{{
      service:
        name: "{{ item }}"
        state: started
        enabled: yes
      with_items:
        - sysstat
        - monit
      ignore_errors: yes
      # }}}

    - name: 清理无用的安装包缓存 # {{{ | Debian
      apt:
        autoclean: yes
      when: ansible_os_family == "Debian"
      # }}}

    - name:  清理不再使用的依赖包 # {{{ | Debian
      apt:
        autoremove: yes
      when: ansible_os_family == "Debian"
      # }}}

    - name: 清理下载的安装包缓存 #  {{{ | Debian
      shell: apt clean && apt autoclean
      ignore_errors: yes
      when: ansible_os_family == "Debian"
      # }}}

    - name: 卸载snapd # {{{ | Debian
      shell: apt -y autoremove --purge snapd
      ignore_errors: yes
      when: ansible_os_family == "Debian"
      # }}}

    - name: 清理安装包 # {{{ | Redhat
      shell: yum clean all
      ignore_errors: true
      when: ansible_os_family == "RedHat"
      # }}}

# {{{ 安装其他软件
- import_playbook: "rar.yml"

- import_playbook: "ccat.yml"
# }}}
