- name: Install mysql-5.7.28
  hosts: all
  tags: mysql
  environment: "{{ proxy_env }}"
  vars:
    mysql_root_dir: /var/lib/mysql
    mysql_config_file: /etc/my.cnf
    mysql_log_dir: /var/log/mysql
    mysql_run_dir: /var/run/mysql
    mysql_pre_dir: /usr/share/mysql
  roles:
    - role: roles/leif160519.mysql
