##
# 设置静态IP地址 
#
#
##
# @leif160519 @2020.09.05
####
---
- name: 设置静态IP
  hosts: all
  tags: network
  tasks:
    - shell: uuid
      register: network_uuid

    - set_fact:
        ubuntu_version: 18.04
        interface: "{{ ansible_default_ipv4['interface'] }}"
        uuid: "{{ network_uuid.stdout }}"
        address: "{{ ansible_default_ipv4['address'] }}"
        netmask: "{{ ansible_default_ipv4['netmask'] }}"
        gateway: "{{ ansible_default_ipv4['gateway'] }}"
        dns1: 180.76.76.76
        dns2: 114.114.114.114

    - shell: |
        maskdigits () {
            a=$(echo "$1" | awk -F "." '{print $1" "$2" "$3" "$4}')
            for num in $a;
            do
                while [ $num != 0 ];do
                echo -n $(($num%2)) >> /tmp/num;
                num=$(($num/2));
                done
            done
            echo $(grep -o "1" /tmp/num | wc -l)
            rm /tmp/num
        }
        maskdigits "{{ netmask }}"
      register: netmask_new

    - set_fact:
        netmask1: "{{ netmask_new.stdout }}"

    - template: # ip地址设置，针对18.04及以上的Ubuntu
        src: files/network/00-installer-config.yaml
        dest: /etc/netplan/00-installer-config.yaml
        mode: 0644
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version(ubuntu_version,">=")

    - template: # ip地址设置，针对18.04之前的Ubuntu和Debian
        src: files/network/interfaces
        dest: /etc/network/interfaces
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_version is version(ubuntu_version,"<")) or (ansible_distribution == "Debian")

    - template: # dns设置，针对18.04之前的Ubuntu和Debian
        src: files/network/resolv.conf
        dest: /etc/resolv.conf
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_version is version(ubuntu_version,"<")) or (ansible_distribution == "Debian")

    - template:
        src: files/network/ifcfg-eth0
        dest: /etc/sysconfig/network-scripts/ifcfg-{{ interface }}
        mode: 0644
      when: ansible_os_family == "RedHat"

    - shell: netplan apply
      when: ansible_distribution == "Ubuntu" and ansible_distribution_version is version(ubuntu_version,">=")

    - service: # 重启网络服务，针对18.04之前的Ubuntu和Debian
        name: networking
        state: restarted
      when: (ansible_distribution == "Ubuntu" and ansible_distribution_version is version(ubuntu_version,"<"))  or (ansible_distribution == "Debian")

    - service: 
        name: network
        state: restarted
      when: ansible_os_family == "RedHat"

