- name: 设置静态IP
  hosts: all
  tags: network
  environment: "{{ proxy_env }}"
  vars:
    dns1: 180.76.76.76
    dns2: 114.114.114.114
    search: localdomain
  roles:
    - role: roles/leif160519.network
