##
# 设置ntp时间同步
#
#
##
# @leif160519 @2020.09.05
# 注意：uubuntu20.04的系统请将ansible版本升级至2.9.8以上或使用2.10(使用pip3而不是apt)，详情参看：https://github.com/geerlingguy/ansible-role-ntp/issues/86
####
---
- name: 设置ntp时间同步
  hosts: all
  tags: ntp
  roles:
    - role: roles/geerlingguy.ntp
      ntp_enabled: true
      ntp_timezone: "Asia/Shanghai"
      ntp_manage_config: true
      ntp_servers:
        - "ntp{{ '.' + ntp_area if ntp_area else '' }}.aliyun.com"
        - "ntp1{{ '.' + ntp_area if ntp_area else '' }}.aliyun.com"
        - "ntp2{{ '.' + ntp_area if ntp_area else '' }}.aliyun.com"
        - "ntp3{{ '.' + ntp_area if ntp_area else '' }}.aliyun.com"
      ntp_restrict:
        - "127.0.0.1"
        - "::1"
      ntp_cron_handler_enabled: true
      ntp_tinker_panic: true
