##
# 安装rar
#
#
##
# @leif160519 @2020.08.29
####
---
- name: 安装rar
  hosts: dist.centos
  tags: rar
  environment: "{{ proxy_env }}"
  vars:
    rar_version_x64: rarlinux-x64-5.7.1
    rar_version_x32: rarlinux-5.7.1
    rar_url_x64: http://www.rarlab.com/rar/{{ rar_version_x64 }}.tar.gz
    rar_url_x32: http://www.rarlab.com/rar/{{ rar_version_x32 }}.tar.gz
  tasks:
    - stat:
        path: /usr/local/bin/rar
      register: rar_cmd

    - unarchive:
        copy: false
        src: "{{ rar_url_x64 }}"
        dest: /tmp
        owner: root
        group: root
      when: (ansible_machine == "x86_64") and (rar_cmd.stat.exists == false)

    - unarchive:
        copy: false
        src: "{{ rar_url_x32 }}"
        dest: /tmp
        owner: root
        group: root
      when: (not ansible_machine == "x86_64") and (rar_cmd.stat.exists == false)

    - shell: |
        cd /tmp/rar/
        make
      ignore_errors: yes
      when: rar_cmd.stat.exists == false
