##
# 安装rar
#
#
##
# @leif160519 @2020.08.29
####
---
- name: 安装rar
  hosts: all
  tags: [rar]
  vars:
    rar_version: 5.7.1
    rar_md5sum_x64: a5a4e30aa7d3591e0b18835fff5906e5
    rar_md5sum_x86: 845b83f6b670877033a6a944a454c47d
  tasks:
    - name: 下载rar安装包
      block:
        - stat:
            path: /tmp/rar
          register: rar

        - get_url:
            url: http://www.rarlab.com/rar/rarlinux-x64-{{ rar_version }}.tar.gz
            dest: /tmp/rarlinux-{{ rar_version }}.tar.gz
            checksum: md5:{{ rar_md5sum_x64 }}
          when: ansible_machine == "x86_64" and rar.stat.exists == false

        - get_url:
            url: http://www.rarsoft.com/rar/rarlinux-{{ rar_version }}.tar.gz
            dest: /tmp/rarlinux-{{ rar_version }}.tar.gz
            checksum: md5:{{ rar_md5sum_x86 }}
          when: not ansible_machine == "x86_64" and rar.stat.exists == false

        - unarchive: 
            copy: false
            src: /tmp/rarlinux-{{ rar_version }}.tar.gz
            dest: /tmp
            owner: root
            group: root
          when: rar.stat.exists == false

        - shell: |
            cd /tmp/rar/
            make
          ignore_errors: yes

        - file:
            path: /tmp/rar
            state: absent
          when: rar.stat.exists == true

        - file:
            path: /tmp/rarlinux-{{ rar_version }}.tar.gz
            state: absent
