##
# 安装rar
#
#
##
# @leif160519 @2020.08.29
####
---
- name: 安装rar
  hosts: all
  tags: [rar]
  vars:
    rar_version_x64: rarlinux-x64-5.7.1
    rar_version_x32: rarlinux-5.7.1
    rar_url_x64: http://10.1.1.26/repository/it/rar/{{ rar_version_x64 }}.tar.gz
    #rar_url_x64: http://www.rarlab.com/rar/{{ rar_version_x64 }}.tar.gz
    rar_url_x32: http://10.1.1.26/repository/it/rar/{{ rar_version_x32 }}.tar.gz
    #rar_url_x32: http://www.rarlab.com/rar/{{ rar_version_x32 }}.tar.gz
    rar_md5sum_x64: a5a4e30aa7d3591e0b18835fff5906e5
    rar_md5sum_x32: 845b83f6b670877033a6a944a454c47d
  tasks:
    - name: rar
      block:
        - stat:
            path: /tmp/rar
          register: rar

        - get_url:
            url: "{{ rar_url_x64 }}" 
            dest: /tmp/{{ rar_version_x32 }}.tar.gz
            checksum: md5:{{ rar_md5sum_x64 }}
          when: ansible_machine == "x86_64" and rar.stat.exists == false

        - get_url:
            url: "{{ rar_url_x32 }}" 
            dest: /tmp/{{ rar_version_x32 }}.tar.gz
            checksum: md5:{{ rar_md5sum_x32 }}
          when: not ansible_machine == "x86_64" and rar.stat.exists == false

        - unarchive: 
            copy: false
            src: /tmp/{{ rar_version_x32 }}.tar.gz
            dest: /tmp
            owner: root
            group: root
          when: rar.stat.exists == false

        - shell: |
            cd /tmp/rar/
            make
          ignore_errors: yes

        - file:
            path: /tmp/rar
            state: absent
          when: rar.stat.exists == true

        - file:
            path: /tmp/rarlinux-{{ rar_version }}.tar.gz
            state: absent
