##
# 设置软件包管理器的镜像源
#
#
##
# @leif160519 @2020.08.29
####
---
- name: Ubuntu LTS # {{{
  hosts: dist.ubuntu.lts
  tags: [ubuntu, lts]
  vars:
    mirror: http://mirrors.aliyun.com/ubuntu/
  tasks:
    - template:
        backup: yes
        src: files/repository/sources.list.j2
        dest: /etc/apt/sources.list
    - apt:
        update_cache: yes
# }}}

- name: Centos # {{{
  hosts: dist.centos
  tags: [centos]
  tasks:
    - get_url:
        backup: yes
        url: http://mirrors.aliyun.com/repo/Centos-{{ ansible_distribution_major_version }}.repo
        dest: /etc/yum.repos.d/CentOS-Base.repo
    - yum:
        update_cache: yes
# }}}

- name: Debian # {{{
  hosts: dist.debian:!dist.ubuntu
  tags: debian
  vars:
    mirror: http://mirrors.aliyun.com/debian/
    mirror_security: http://mirrors.aliyun.com/debian-security
  tasks:
    - template:
        backup: yes
        src: files/repository/sources-debian.list.j2
        dest: /etc/apt/sources.list
    - apt:
       update_cache: yes
# }}}
