##
# 生成sshkey
#
#
##
# @leif160519 @2020.09.03
# 默认生成root用户的sshkey，若对多用户生成sshkey，可跟上参数-e username='["root","ubuntu"]'
####
---
- name: 生成sshkey
  hosts: all
  vars:
    username: root
  tags: ssh
  tasks:
    - user:
        name: "{{ item }}"
        comment: "{{ item }}"
        group: "{{ item }}"
        generate_ssh_key: yes
        ssh_key_file: ~{{ item }}/.ssh/id_rsa
        state: present
      with_items:
        - "{{ username }}"
      ignore_errors: yes
