##
# 通用的配置，集成在这个顶层剧本中
##
# @2020.08 @leif160519
####
---
# 软件源仓库
- import_playbook: repository.yml

# 安装软件
- import_playbook: install.yml

# 系统配置
- import_playbook: config.yml

# 生成ssh-key
- import_playbook: ssh-key.yml

# 设置ntp时间同步
- import_playbook: ntp.yml

# 设置静态IP地址
- import_playbook: network.yml

# 安装rar
- import_playbook: rar.yml

# 安装node_exporter
- import_playbook: prometheus.yml
